AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  SAM Template for LifeHack-2023

Parameters:
  AppName:
    Type: String
    Description: "Name of Application"
    Default: "LifeHack-Backend"
    AllowedPattern: ".+"
  AppRegion:
    Type: String
    Default: "ap-southeast-1"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  # HelloWorldFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     PackageType: Image
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /hello
  #           Method: get
  #   Metadata:
  #     Dockerfile: Dockerfile
  #     DockerContext: ./hello_world
  #     DockerTag: python3.9-v1
  OpenAIAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: >
        Boilerplate function to query GPT 3.5-Turbo
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        postOpenAI:
          Type: Api
          Properties:
            Path: /postOpenAI
            Method: post
    Metadata:
      DockerTag: python3.9
      DockerContext: functions/openai_api
      Dockerfile: Dockerfile

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
